### ISSUE TITLE
Ideas for uploading the main parts of the pools script

### ISSUE THREAD

**Issue by trentgill** [isaacpearl/pools#15]
-- in the uploaded script
`function has_pools() _c.tell('pools') end`

The startup routine in pools would look something like (JS pseudocode)
```
has_pools() -- calls to crow to run the has_pools function, which should return `^^pools()`
sleep 100 -- wait for the response
if not indeed_there_is_pools! then -- indeed_there_is_pools is a global in JS that is set below
  upload pools
end
reset() -- need to do this regardless of whether we uploaded or not
```

This is in JS to match against the returned message from crow
```
-- callback matching `^^pools()` or `^^pools`
function matched_pools()
    indeed_there_is_pools! = true
end
```

-- reset the env
This could actually live in crow so it could be called when loading a pools script.
```
function reset_pools()
    for n=1,4 do output[n]( to(0) ) end
    events = {}
    pools = {}
    init()
end
```

**Comment by isaacpearl** [comment]
This is working! the only problem is that consecutive uploads aren't overwriting what was there before - you have to hard reset crow multiple times before you have a fresh slate. 

this can be confirmed by:
1. uploading the pools script (by starting up pools)
2. closing the application
3. uploading a new script in druid
4.  sending a message with references to the _pools_ state script like ```print(pools)``` in druid
5. the above will return a table reference, when it should return nil

**Comment by isaacpearl** [comment]
this is working! if you need to send a new version of the lua script, send ^^c and ^^k in druid, then quit.
